version: '3.3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - C:\volumes\sd\keycloak:/opt/keycloak/data/import/
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - "start-dev"
      - "--import-realm"
      - "--db postgres"
      - "--db-url jdbc:postgresql://keycloak_db:5432/keycloak"
      - "--db-username postgres"
      - "--db-password postgres"
    depends_on:
      - keycloak_db
    restart: always
    networks:
      backend:
80
  keycloak_db:
    container_name: keycloak_db
    image: 'postgres'
    ports:
      - "4042:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - C:\volumes\sd\postgres\keycloak:/var/lib/postgresql/data/
    networks:
      backend:

  users_db:
    container_name: person_db
    image: 'postgres'
    ports:
      - "4040:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=person
    volumes:
      - C:\volumes\sd\postgres\person:/var/lib/postgresql/data/
    networks:
      backend:

  device_db:
    container_name: device_db
    image: 'postgres'
    ports:
      - "4041:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=device
    volumes:
      - C:\volumes\sd\postgres\device:/var/lib/postgresql/data/
    networks:
      backend:

  monitor_db:
    container_name: monitor_db
    image: 'postgres'
    ports:
      - "4043:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitor
    volumes:
      - C:\volumes\sd\postgres\monitor:/var/lib/postgresql/data/
    networks:
      backend:

  chat_db:
    container_name: chat_db
    image: 'postgres'
    ports:
      - "4044:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    volumes:
      - C:\volumes\sd\postgres\chat:/var/lib/postgresql/data/
    networks:
      backend:


  ems_person:
    container_name: ems-person
    image: 'ems-person'
    ports:
      - "8080:8080"
    depends_on:
      - users_db
      - keycloak
    restart: always
    networks:
      backend:

  ems_rabby:
    container_name: ems-rabby
    image: 'ems-rabby'
    ports:
      - "8086:8086"
    depends_on:
        - rabbitmq
    restart: always
    networks:
      backend:



  ems_device:
    container_name: ems-device
    image: 'ems-device'
    ports:
      - "8081:8081"
    depends_on:
      - device_db
      - keycloak
    restart: always
    networks:
      backend:


  ems_chat:
    container_name: ems-chat
    image: 'ems-chat'
    ports:
      - "8091:8091"
    depends_on:
      - chat_db
      - keycloak
    restart: always
    networks:
      backend:


  frontend:
    container_name: frontend
    image: 'frontend'
    ports:
      - "3000:3000"
    restart: always
    networks:
        backend:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      backend:




networks:
  backend:
