# DataSource Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://chat_db:5432/chat

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ems
          jwk-set-uri: http://keycloak:8080/realms/ems/protocol/openid-connect/certs

  # Flyway Configuration
  flyway:
    locations: classpath:db/migration

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# External Configuration
external:
  webclient:
    keycloak: http://localhost:8080

jwt:
  auth:
    converter:
      resource-id: ems-chat
      principle-attribute: preferred_username


# Server Port Configuration
server:
  port: 8091
